name: WealthSpring Investments
favicon: null
layout_spectrum: 0.5832283301278949
typography_spectrum: 0.26355629158206284
title: The Journey of A New Real Estate Investment Firm
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#1eaee8'
    - '#f1923e'
    - '#e7328b'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
