name: WealthSpring Investments
favicon: null
layout_spectrum: 0.5832283301278949
typography_spectrum: 0.26355629158206284
title: The Journey of A New Real Estate Investment Firm
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.008204735117033124
  lightness: 0.8019047847483307
  saturation: 0.03220852161757648
  rhythmicContrast: 0.541929620783776
purpose: []
